// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuJdi0WY8JutF96to5yTDQ32S0zmu4_DU',
    appId: '1:662602640602:web:cab23aefb6185812c189e3',
    messagingSenderId: '662602640602',
    projectId: 'bloc-learning-app',
    authDomain: 'bloc-learning-app.firebaseapp.com',
    storageBucket: 'bloc-learning-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMxwlKFdNrA-SPEwAV9gcOQUFgLw2NYEc',
    appId: '1:662602640602:android:30c61b28d5817949c189e3',
    messagingSenderId: '662602640602',
    projectId: 'bloc-learning-app',
    storageBucket: 'bloc-learning-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9H3TfSMgzhNhQcXs0tXjxfcpzWLCZP10',
    appId: '1:662602640602:ios:feb554f81d60e6e5c189e3',
    messagingSenderId: '662602640602',
    projectId: 'bloc-learning-app',
    storageBucket: 'bloc-learning-app.appspot.com',
    iosClientId: '662602640602-j860ls8lidca2kmu3l7t25ivdg2fi5ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9H3TfSMgzhNhQcXs0tXjxfcpzWLCZP10',
    appId: '1:662602640602:ios:feb554f81d60e6e5c189e3',
    messagingSenderId: '662602640602',
    projectId: 'bloc-learning-app',
    storageBucket: 'bloc-learning-app.appspot.com',
    iosClientId: '662602640602-j860ls8lidca2kmu3l7t25ivdg2fi5ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );
}
